CC = arm-linux-gnueabihf-gcc
CFLAGS = -g -std=c99 -Wall -Werror
SOURCES = main.c
OUT_DIR = $(HOME)/cmpt433/public/myApps

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(OUT_DIR)/find-dot

clean:
	rm $(OUT_DIR)/find-dot

